version: "1.0"
feature_name: unified-checkout-2930f501
branch: feat/unified-checkout-2930f501
repos:
    - name: demo-payment-svc
      url: https://github.com/iron-s/demo-payment-svc
      path: /Users/iron/macr-demo/demo-payment-svc
      pointer_type: sha
      current_pointer: 1221cc8d821e86d8d5539b56782ba5d6cdb7fe4d
      branch: feat/unified-checkout-2930f501
